---
remotes:
  vendor: https://github.com/wayneeseguin/rvm
  primary: git@github.com:destructuring/rvm
  secondary: git@bitbucket.org:destructuring/rvm
  sh: https://github.com/destructuring/jason
  bump: https://github.com/destructuring/mixin-bump
